GET http://localhost:8080/api/v1/user/list-of-app-users
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbEBlbWFpbC5jb20iLCJpYXQiOjE2ODQxNDQxNTAsImV4cCI6MTY4NDE0NTU5MH0.ieQ4k26lmxyiKxRtAAddB_3zGHcWwY2L9Tk1gIXLv5E"
}

###